version: '3'

services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      PHP_INI_SCAN_DIR: /usr/local/etc/php/conf.d:/var/www/html/php
    networks:
      - my-network

  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'laraapp_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

networks:
  my-network: